//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wellcome.Dds.MillenniumClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapps.iii.com/wsclient/patronio", ConfigurationName="Wellcome.Dds.MillenniumClient.PatronIO")]
    public interface PatronIO
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronFine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinePaymentElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchPatronsReturn")]
        System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> searchPatronsAsync(string username, string password, string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronFine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinePaymentElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createPatronReturn")]
        System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> createPatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronFine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinePaymentElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updatePatronReturn")]
        System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> updatePatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronFine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinePaymentElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="payPatronFineReturn")]
        System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> payPatronFineAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronFine))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatronField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FinePaymentElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deletePatronReturn")]
        System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> deletePatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webapps.iii.com/wsclient/patronio")]
    public partial class Patron
    {
        
        private FinePaymentElement[] finePaymentField;
        
        private PatronField[] patronFieldsField;
        
        private PatronFine[] patronFinesField;
        
        private string patronIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FinePaymentElement[] finePayment
        {
            get
            {
                return this.finePaymentField;
            }
            set
            {
                this.finePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PatronField[] patronFields
        {
            get
            {
                return this.patronFieldsField;
            }
            set
            {
                this.patronFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PatronFine[] patronFines
        {
            get
            {
                return this.patronFinesField;
            }
            set
            {
                this.patronFinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string patronID
        {
            get
            {
                return this.patronIDField;
            }
            set
            {
                this.patronIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webapps.iii.com/wsclient/patronio")]
    public partial class FinePaymentElement
    {
        
        private int amountField;
        
        private string initialsField;
        
        private string invoiceField;
        
        private string typeField;
        
        /// <remarks/>
        public int amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webapps.iii.com/wsclient/patronio")]
    public partial class PatronFine
    {
        
        private int amountPaidField;
        
        private int billingFeeField;
        
        private string campusCodeField;
        
        private string chargeLocationField;
        
        private string chargeTypeField;
        
        private string collectorInitialsField;
        
        private string creationMethodField;
        
        private System.Nullable<System.DateTime> dateAssessedField;
        
        private System.Nullable<System.DateTime> datePaidField;
        
        private string descriptionField;
        
        private int invoiceField;
        
        private int itemChargeField;
        
        private System.Nullable<System.DateTime> itemCheckoutDateField;
        
        private System.Nullable<System.DateTime> itemDateReturnedField;
        
        private System.Nullable<System.DateTime> itemDueDateField;
        
        private int itemLoanRuleField;
        
        private int itemRecordNumField;
        
        private string itemTitleField;
        
        private int occurrenceField;
        
        private int originalPatronIDField;
        
        private int patronIDField;
        
        private bool printBillField;
        
        private int processingFeeField;
        
        private int terminalPaidAtField;
        
        private System.Nullable<System.DateTime> transferDateField;
        
        /// <remarks/>
        public int amountPaid
        {
            get
            {
                return this.amountPaidField;
            }
            set
            {
                this.amountPaidField = value;
            }
        }
        
        /// <remarks/>
        public int billingFee
        {
            get
            {
                return this.billingFeeField;
            }
            set
            {
                this.billingFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string campusCode
        {
            get
            {
                return this.campusCodeField;
            }
            set
            {
                this.campusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string chargeLocation
        {
            get
            {
                return this.chargeLocationField;
            }
            set
            {
                this.chargeLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string chargeType
        {
            get
            {
                return this.chargeTypeField;
            }
            set
            {
                this.chargeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string collectorInitials
        {
            get
            {
                return this.collectorInitialsField;
            }
            set
            {
                this.collectorInitialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creationMethod
        {
            get
            {
                return this.creationMethodField;
            }
            set
            {
                this.creationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dateAssessed
        {
            get
            {
                return this.dateAssessedField;
            }
            set
            {
                this.dateAssessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> datePaid
        {
            get
            {
                return this.datePaidField;
            }
            set
            {
                this.datePaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public int itemCharge
        {
            get
            {
                return this.itemChargeField;
            }
            set
            {
                this.itemChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> itemCheckoutDate
        {
            get
            {
                return this.itemCheckoutDateField;
            }
            set
            {
                this.itemCheckoutDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> itemDateReturned
        {
            get
            {
                return this.itemDateReturnedField;
            }
            set
            {
                this.itemDateReturnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> itemDueDate
        {
            get
            {
                return this.itemDueDateField;
            }
            set
            {
                this.itemDueDateField = value;
            }
        }
        
        /// <remarks/>
        public int itemLoanRule
        {
            get
            {
                return this.itemLoanRuleField;
            }
            set
            {
                this.itemLoanRuleField = value;
            }
        }
        
        /// <remarks/>
        public int itemRecordNum
        {
            get
            {
                return this.itemRecordNumField;
            }
            set
            {
                this.itemRecordNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string itemTitle
        {
            get
            {
                return this.itemTitleField;
            }
            set
            {
                this.itemTitleField = value;
            }
        }
        
        /// <remarks/>
        public int occurrence
        {
            get
            {
                return this.occurrenceField;
            }
            set
            {
                this.occurrenceField = value;
            }
        }
        
        /// <remarks/>
        public int originalPatronID
        {
            get
            {
                return this.originalPatronIDField;
            }
            set
            {
                this.originalPatronIDField = value;
            }
        }
        
        /// <remarks/>
        public int patronID
        {
            get
            {
                return this.patronIDField;
            }
            set
            {
                this.patronIDField = value;
            }
        }
        
        /// <remarks/>
        public bool printBill
        {
            get
            {
                return this.printBillField;
            }
            set
            {
                this.printBillField = value;
            }
        }
        
        /// <remarks/>
        public int processingFee
        {
            get
            {
                return this.processingFeeField;
            }
            set
            {
                this.processingFeeField = value;
            }
        }
        
        /// <remarks/>
        public int terminalPaidAt
        {
            get
            {
                return this.terminalPaidAtField;
            }
            set
            {
                this.terminalPaidAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> transferDate
        {
            get
            {
                return this.transferDateField;
            }
            set
            {
                this.transferDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://webapps.iii.com/wsclient/patronio")]
    public partial class PatronField
    {
        
        private string fieldTagField;
        
        private string marcTagField;
        
        private string valueField;
        
        private bool valueIsBinaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fieldTag
        {
            get
            {
                return this.fieldTagField;
            }
            set
            {
                this.fieldTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string marcTag
        {
            get
            {
                return this.marcTagField;
            }
            set
            {
                this.marcTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool valueIsBinary
        {
            get
            {
                return this.valueIsBinaryField;
            }
            set
            {
                this.valueIsBinaryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PatronIOChannel : Wellcome.Dds.MillenniumClient.PatronIO, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PatronIOClient : System.ServiceModel.ClientBase<Wellcome.Dds.MillenniumClient.PatronIO>, Wellcome.Dds.MillenniumClient.PatronIO
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PatronIOClient() : 
                base(PatronIOClient.GetDefaultBinding(), PatronIOClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PatronIO.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatronIOClient(EndpointConfiguration endpointConfiguration) : 
                base(PatronIOClient.GetBindingForEndpoint(endpointConfiguration), PatronIOClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatronIOClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PatronIOClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatronIOClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PatronIOClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatronIOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> searchPatronsAsync(string username, string password, string searchString)
        {
            return base.Channel.searchPatronsAsync(username, password, searchString);
        }
        
        public System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> createPatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron)
        {
            return base.Channel.createPatronAsync(username, password, patron);
        }
        
        public System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> updatePatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron)
        {
            return base.Channel.updatePatronAsync(username, password, patron);
        }
        
        public System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> payPatronFineAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron)
        {
            return base.Channel.payPatronFineAsync(username, password, patron);
        }
        
        public System.Threading.Tasks.Task<Wellcome.Dds.MillenniumClient.Patron> deletePatronAsync(string username, string password, Wellcome.Dds.MillenniumClient.Patron patron)
        {
            return base.Channel.deletePatronAsync(username, password, patron);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PatronIO))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PatronIO))
            {
                return new System.ServiceModel.EndpointAddress("https://catalogue.wellcomelibrary.org:843/iii/patronio/services/PatronIO");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PatronIOClient.GetBindingForEndpoint(EndpointConfiguration.PatronIO);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PatronIOClient.GetEndpointAddress(EndpointConfiguration.PatronIO);
        }
        
        public enum EndpointConfiguration
        {
            
            PatronIO,
        }
    }
}
